[package]
name = "twodo"
authors = ["Jobin Nelson"]
description = "This a simple todo list application in terminal"
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
